### ISSUE TITLE
显示输出外接

### ISSUE THREAD

**Issue by flyinghappyking** [SunSeekerX/hasee-g8-ca5ns-NH5x_7xDPx-hackintosh-opencore-efi#1]
你好，非常高兴看到你的尝试。
我的也是这个CA5NS型号，配置一致的。我自己配置不成功，后来网上买了一个，但是也不完美，比如：触摸板下面的两个按键无法操作，睡眠，电量无显示等。但是声音属于半正常，冷启动，声音有；但如果从windows下面重启，就会发现无声音。另外一个比较大的影响，是无法外接显示器，我想要的就是个大显示器，不知道你的这个可以吗？通过什么口输出？

**Comment by flyinghappyking** [comment]
还有，你有没有设置那个cpu lock寄存器？我找不到改的地方，BIOS升级了也没有，VBIOS不知如何升。

**Comment by SunSeekerX** [comment]
> 你好，非常高兴看到你的尝试。 我的也是这个CA5NS型号，配置一致的。我自己配置不成功，后来网上买了一个，但是也不完美，比如：触摸板下面的两个按键无法操作，睡眠，电量无显示等。但是声音属于半正常，冷启动，声音有；但如果从windows下面重启，就会发现无声音。另外一个比较大的影响，是无法外接显示器，我想要的就是个大显示器，不知道你的这个可以吗？通过什么口输出？

外接显示器应该是不可以的，HDMI口应该是独显直连的，还有一个迷你dp，你可以试一下

**Comment by SunSeekerX** [comment]
> 你好，非常高兴看到你的尝试。 我的也是这个CA5NS型号，配置一致的。我自己配置不成功，后来网上买了一个，但是也不完美，比如：触摸板下面的两个按键无法操作，睡眠，电量无显示等。但是声音属于半正常，冷启动，声音有；但如果从windows下面重启，就会发现无声音。另外一个比较大的影响，是无法外接显示器，我想要的就是个大显示器，不知道你的这个可以吗？通过什么口输出？

有联系方式吗？你的声音正常，看一下你的oc配置，我这个也电量不显示，睡眠的话，我不用这个功能。触摸板上面那两个按键和电量应该都要那个dsd t去解决

**Comment by SunSeekerX** [comment]
> 还有，你有没有设置那个cpu lock寄存器？我找不到改的地方，BIOS升级了也没有，VBIOS不知如何升。

我就把硬盘模式改了下，其他的应该没有关系的，这个主板的bios非常简单

**Comment by flyinghappyking** [comment]
> 

我试过通过mDP转HDMI，但是仍无显示。

**Comment by flyinghappyking** [comment]
> > 你好，非常高兴看到你的尝试。 我的也是这个CA5NS型号，配置一致的。我自己配置不成功，后来网上买了一个，但是也不完美，比如：触摸板下面的两个按键无法操作，睡眠，电量无显示等。但是声音属于半正常，冷启动，声音有；但如果从windows下面重启，就会发现无声音。另外一个比较大的影响，是无法外接显示器，我想要的就是个大显示器，不知道你的这个可以吗？通过什么口输出？
> 
> 有联系方式吗？你的声音正常，看一下你的oc配置，我这个也电量不显示，睡眠的话，我不用这个功能。触摸板上面那两个按键和电量应该都要那个dsd t去解决
我的是用的clover，是通用的声卡，我用的ID是29.

**Comment by flyinghappyking** [comment]
> > 还有，你有没有设置那个cpu lock寄存器？我找不到改的地方，BIOS升级了也没有，VBIOS不知如何升。
> 
> 我就把硬盘模式改了下，其他的应该没有关系的，这个主板的bios非常简单

网上的通过直接修改CPU的无法实现。
