### ISSUE TITLE
等你出cfg lock解锁的教程哟

### ISSUE THREAD

**Issue by flyinghappyking** [SunSeekerX/hasee-g8-ca5ns-NH5x_7xDPx-hackintosh-opencore-efi#2]
按网上的教程，设置不成功。所以一用黑苹果，电脑风扇就呼呼地转。
期待你的教程，谢谢了！

**Comment by SunSeekerX** [comment]
> 按网上的教程，设置不成功。所以一用黑苹果，电脑风扇就呼呼地转。 期待你的教程，谢谢了！

https://github.com/SunSeekerX/hasee-g8-ca5ns-NH5x_7xDPx-hackintosh-opencore-efi/issues/2#issue-1608743032

**Comment by SunSeekerX** [comment]
> 按网上的教程，设置不成功。所以一用黑苹果，电脑风扇就呼呼地转。 期待你的教程，谢谢了！

https://doc.yoouu.cn/interest/hackintosh.html#%E7%A5%9E%E8%88%9F-hasee-g8-ca5ns-nh5x-7xdpx

**Comment by flyinghappyking** [comment]
谢谢了，晚上回家里试一试

**Comment by flyinghappyking** [comment]
very good, 这是最可行的开启方式了。那个CFG利用其它方式都是设置不成功，这个昨天搞好后，电脑不会一直呼呼的转了。
