### ISSUE TITLE
wifi 无线不可用

### ISSUE THREAD

**Issue by liloew** [SunSeekerX/hasee-g8-ca5ns-NH5x_7xDPx-hackintosh-opencore-efi#4]
麻烦问下原装的 9462 是否可以驱动？
看 README 中好像你用的是 AX200，是因为原装 9462 驱动不起来吗还是什么原因？
看 [OpenIntelWireless/itlwm](https://github.com/OpenIntelWireless/itlwm) 的兼容性列表应该是支持 9462 的。

**Comment by SunSeekerX** [comment]
> 麻烦问下原装的 9462 是否可以驱动？ 看 README 中好像你用的是 AX200，是因为原装 9462 驱动不起来吗还是什么原因？ 看 [OpenIntelWireless/itlwm](https://github.com/OpenIntelWireless/itlwm) 的兼容性列表应该是支持 9462 的。

应该是没问题的，原装的我送给别人了，多了一块200的网卡我就放进去了

**Comment by liloew** [comment]
我现在用的是原装的网卡，但是不行。现象是可以连上 wifi，但是menu bar 上无线图标是感叹号，ifconfig 看没有获取到 ip 地址。
试过更换 itlwm 的 kext 也不行，包括最新 alpha 版本的。
请问 wifi 这块还需要改其他配置吗？

**Comment by SunSeekerX** [comment]
> 我现在用的是原装的网卡，但是不行。现象是可以连上 wifi，但是menu bar 上无线图标是感叹号，ifconfig 看没有获取到 ip 地址。 试过更换 itlwm 的 kext 也不行，包括最新 alpha 版本的。 请问 wifi 这块还需要改其他配置吗？

要装那个客户端 新的阿尔法版本有问题 那个在文档里面已经说了 你在苹果这边从WINDOWS下用U盘下载一个客户端过来 用客户端连接WIFI那个系统 自带的那个WIFI连接界面用不了

**Comment by liloew** [comment]
> 

[OpenIntelWireless/HeliPort](https://github.com/OpenIntelWireless/HeliPort) 这个吗？已经安装了，但是不行，重启多次了

**Comment by SunSeekerX** [comment]
> > 
> 
> [OpenIntelWireless/HeliPort](https://github.com/OpenIntelWireless/HeliPort) 这个吗？已经安装了，但是不行，重启多次了

安装重启之后 在那个右上角没有WIFI显示吗 不是系统那个 是他会自己出来多一个

**Comment by liloew** [comment]
> > > 
> > 
> > 
> > [OpenIntelWireless/HeliPort](https://github.com/OpenIntelWireless/HeliPort) 这个吗？已经安装了，但是不行，重启多次了
> 
> 安装重启之后 在那个右上角没有WIFI显示吗 不是系统那个 是他会自己出来多一个

系统原生的 wifi 管理是有感叹号不能用的，但是打开 HeliPort 后也会出现中 menubar 上面，连接 wifi 后显示和原生的一样，有感叹号不能用。

另外黑苹果我用过好多了，这个还是了解的哈。根据我的了解，即使你的 EFI 里面 itlwm 这个驱动有问题，直接替换原生的然后刷新 kext 应该就没问题才对，所以不太清楚还是否还需要修改 config.plist 文件

**Comment by liloew** [comment]
![WIFI](https://user-images.githubusercontent.com/4378795/226599786-dcc7a87b-642b-48e7-a38e-d567b40f5b97.png)

使用 HeliPort 连接 wifi 如上图，左边的是 HeliPort，右侧的是系统原生的 wifi 管理。
现在是新换来一块 AX200 的网卡，也是这样。

**Comment by liloew** [comment]
> > ![WIFI](https://user-images.githubusercontent.com/4378795/226599786-dcc7a87b-642b-48e7-a38e-d567b40f5b97.png)
> > 使用 HeliPort 连接 wifi 如上图，左边的是 HeliPort，右侧的是系统原生的 wifi 管理。 现在是新换了一块 AX200 的网卡，也是这样。
> 
> 确定是一样的机型吗，你这有点奇怪，bios 设置有问题吗

BIOS 设置的话刷了官网的 BIOS 后只改了 AHCI 模式。

机型应该是一致的，BIOS 文件通用，参考这里 [http://kfgl.hasee.com/lookup/bios/bios_nb.asp](http://kfgl.hasee.com/lookup/bios/bios_nb.asp)，准系统名称：NHxxDPx
