### ISSUE TITLE
Circle w/ slash error while loading offline installer of hack

### ISSUE THREAD

**Issue by quartzz720** [SunSeekerX/hasee-g8-ca5ns-NH5x_7xDPx-hackintosh-opencore-efi#5]
Hello there! I'm new at hackintosh and I was trying to install the macOS 12.6 Monterey using your opencore.
But now I have some troubles with the installer

![IMG20230522222730](https://github.com/SunSeekerX/hasee-g8-ca5ns-NH5x_7xDPx-hackintosh-opencore-efi/assets/60406432/6a75684a-f8e0-4f6d-8b2c-6a4804a2047a)

![Screenshot_2023-05-22-22-09-18-54_99c04817c0de5652397fc8b56c3b3817](https://github.com/SunSeekerX/hasee-g8-ca5ns-NH5x_7xDPx-hackintosh-opencore-efi/assets/60406432/50a52d91-745b-45c5-9a06-712e4c16efef)

Please help me!

**Comment by quartzz720** [comment]
On screen 2 
There is an error "Still waiting for root device"

**Comment by SunSeekerX** [comment]
> 

I met this error for the first time, hahaha, first of all, you are using the same model as me to get the device? Then you need to enter the bios to modify the hard disk mode for ahci, if you do not unlock the cfg lock, you need to edit the config.plist to check the cfg-related options, and then you try again!

**Comment by quartzz720** [comment]
Thanks for answer!
I'm using hasee ca5nb on the same board + i5-10200h
Hard disk mode is already AHCI, 
CFG is unlocked and I remapped all USB ports.
I don't know what to do :D

**Comment by SunSeekerX** [comment]
> 

Oh, I understand now. There should be a specialized AML file in my ACPI folder to solve the problem of not displaying the charging status. Actually, I'm not very familiar with it and had someone install it for me on Taobao for a fee. If you need, I can help you contact him. His skills are great, but he communicates in Chinese and does remote installations.

**Comment by SunSeekerX** [comment]
> Thanks for answer! I'm using hasee ca5nb with the same board + i5-10200h Hard disk mode is already AHCI, CFG is unlocked and I remapped all USB ports. I don't know what to do :D

Oh, I understand now. There should be a specialized AML file in my ACPI folder to solve the problem of not displaying the charging status. Actually, I'm not very familiar with it and had someone install it for me on Taobao for a fee. If you need, I can help you contact him. His skills are great, but he communicates in Chinese and does remote installations.

**Comment by quartzz720** [comment]
Is this AML file included in ACPI folder?
And yes, please help me contact him :D

**Comment by SunSeekerX** [comment]
> 



> Is this AML file included in ACPI folder at GitHub? And yes, please help me contact him :D

I have uploaded all of them, what is your contact information and do you use wechat?

**Comment by quartzz720** [comment]
> I have uploaded all of them, what is your contact information and do you use wechat?
Ivan K., phone/Whatsapp number is +79653259795
I can't use wechat because it works bad in Russia

**Comment by SunSeekerX** [comment]
Unable to install Hackintosh on 10200h 😥

**Comment by quartzz720** [comment]
Press F to fake UHD 630

**Comment by kaiyuan12345678** [comment]
https://bbs.pcbeta.com/forum.php?mod=viewthread&tid=2064099&highlight=10200
